version: '3.8'
services:
  broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"

  database:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"